# AA Projekt

## Data Collection and Preparation

In [1]:
import numpy as np
import pandas as pd

In [2]:
charging_data = pd.read_csv("charging_sessions.csv", index_col="id")

In [3]:
charging_data.head()

,Unnamed: 0,connectionTime,disconnectTime,doneChargingTime,kWhDelivered,sessionID,siteID,spaceID,stationID,timezone,userID,userInputs
id,,,,,,,,,,,,
5e23b149f9af8b5fe4b973cf,0,2020-01-02 13:08:54+00:00,2020-01-02 19:11:15+00:00,2020-01-02 17:31:35+00:00,25.016,1_1_179_810_2020-01-02 13:08:53.870034,1,AG-3F30,1-1-179-810,America/Los_Angeles,194.0,"[{'WhPerMile': 250, 'kWhRequested': 25.0, 'mil..."
5e23b149f9af8b5fe4b973d0,1,2020-01-02 13:36:50+00:00,2020-01-02 22:38:21+00:00,2020-01-02 20:18:05+00:00,33.097,1_1_193_825_2020-01-02 13:36:49.599853,1,AG-1F01,1-1-193-825,America/Los_Angeles,4275.0,"[{'WhPerMile': 280, 'kWhRequested': 70.0, 'mil..."
5e23b149f9af8b5fe4b973d1,2,2020-01-02 13:56:35+00:00,2020-01-03 00:39:22+00:00,2020-01-02 16:35:06+00:00,6.521,1_1_193_829_2020-01-02 13:56:35.214993,1,AG-1F03,1-1-193-829,America/Los_Angeles,344.0,"[{'WhPerMile': 400, 'kWhRequested': 8.0, 'mile..."
5e23b149f9af8b5fe4b973d2,3,2020-01-02 13:59:58+00:00,2020-01-02 16:38:39+00:00,2020-01-02 15:18:45+00:00,2.355,1_1_193_820_2020-01-02 13:59:58.309319,1,AG-1F04,1-1-193-820,America/Los_Angeles,1117.0,"[{'WhPerMile': 400, 'kWhRequested': 8.0, 'mile..."
5e23b149f9af8b5fe4b973d3,4,2020-01-02 14:00:01+00:00,2020-01-02 22:08:40+00:00,2020-01-02 18:17:30+00:00,13.375,1_1_193_819_2020-01-02 14:00:00.779967,1,AG-1F06,1-1-193-819,America/Los_Angeles,334.0,"[{'WhPerMile': 400, 'kWhRequested': 16.0, 'mil..."

In [4]:
charging_data.describe(include="all")

,Unnamed: 0,connectionTime,disconnectTime,doneChargingTime,kWhDelivered,sessionID,siteID,spaceID,stationID,timezone,userID,userInputs
count,66450.000000,66450,66450,62362,66450.000000,66450,66450.000000,66450,66450,66450,49187.000000,49187
unique,NaN,64839,64906,60637,NaN,65037,NaN,107,107,1,NaN,47822
top,NaN,2019-07-08 14:46:17+00:00,2021-07-22 14:35:55+00:00,2018-10-16 16:40:56+00:00,NaN,1_1_193_816_2019-07-10 13:29:21.499835,NaN,CA-303,2-39-139-28,America/Los_Angeles,NaN,"[{'WhPerMile': 300, 'kWhRequested': 21.0, 'mil..."
freq,NaN,14,7,8,NaN,2,NaN,1805,1805,66450,NaN,2
mean,4726.102062,NaN,NaN,NaN,11.787916,NaN,1.472656,NaN,NaN,NaN,1800.494582,NaN
std,3568.025394,NaN,NaN,NaN,10.314789,NaN,0.499256,NaN,NaN,NaN,2617.548614,NaN
min,0.000000,NaN,NaN,NaN,0.501000,NaN,1.000000,NaN,NaN,NaN,1.000000,NaN
25%,1845.000000,NaN,NaN,NaN,5.097000,NaN,1.000000,NaN,NaN,NaN,431.000000,NaN
50%,3960.000000,NaN,NaN,NaN,9.140000,NaN,1.000000,NaN,NaN,NaN,818.000000,NaN
75%,7027.000000,NaN,NaN,NaN,14.183000,NaN,2.000000,NaN,NaN,NaN,1805.000000,NaN
max,15291.000000,NaN,NaN,NaN,108.797242,NaN,2.000000,NaN,NaN,NaN,19923.000000,NaN

In [5]:
charging_data.columns

Index(['Unnamed: 0', 'connectionTime', 'disconnectTime', 'doneChargingTime',
       'kWhDelivered', 'sessionID', 'siteID', 'spaceID', 'stationID',
       'timezone', 'userID', 'userInputs'],
      dtype='object')

In [6]:
charging_data.notnull()

,Unnamed: 0,connectionTime,disconnectTime,doneChargingTime,kWhDelivered,sessionID,siteID,spaceID,stationID,timezone,userID,userInputs
id,,,,,,,,,,,,
5e23b149f9af8b5fe4b973cf,True,True,True,True,True,True,True,True,True,True,True,True
5e23b149f9af8b5fe4b973d0,True,True,True,True,True,True,True,True,True,True,True,True
5e23b149f9af8b5fe4b973d1,True,True,True,True,True,True,True,True,True,True,True,True
5e23b149f9af8b5fe4b973d2,True,True,True,True,True,True,True,True,True,True,True,True
5e23b149f9af8b5fe4b973d3,True,True,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...
5d574ad2f9af8b4c10c03652,True,True,True,True,True,True,True,True,True,True,True,True
5d574ad2f9af8b4c10c03653,True,True,True,True,True,True,True,True,True,True,True,True
5d574ad2f9af8b4c10c03654,True,True,True,True,True,True,True,True,True,True,True,True
5d574ad2f9af8b4c10c03655,True,True,True,True,True,True,True,True,True,True,True,True
5d574ad2f9af8b4c10c03656,True,True,True,True,True,True,True,True,True,True,False,False

In [7]:
charging_data.drop_duplicates(subset=["sessionID"])

,Unnamed: 0,connectionTime,disconnectTime,doneChargingTime,kWhDelivered,sessionID,siteID,spaceID,stationID,timezone,userID,userInputs
id,,,,,,,,,,,,
5e23b149f9af8b5fe4b973cf,0,2020-01-02 13:08:54+00:00,2020-01-02 19:11:15+00:00,2020-01-02 17:31:35+00:00,25.016,1_1_179_810_2020-01-02 13:08:53.870034,1,AG-3F30,1-1-179-810,America/Los_Angeles,194.0,"[{'WhPerMile': 250, 'kWhRequested': 25.0, 'mil..."
5e23b149f9af8b5fe4b973d0,1,2020-01-02 13:36:50+00:00,2020-01-02 22:38:21+00:00,2020-01-02 20:18:05+00:00,33.097,1_1_193_825_2020-01-02 13:36:49.599853,1,AG-1F01,1-1-193-825,America/Los_Angeles,4275.0,"[{'WhPerMile': 280, 'kWhRequested': 70.0, 'mil..."
5e23b149f9af8b5fe4b973d1,2,2020-01-02 13:56:35+00:00,2020-01-03 00:39:22+00:00,2020-01-02 16:35:06+00:00,6.521,1_1_193_829_2020-01-02 13:56:35.214993,1,AG-1F03,1-1-193-829,America/Los_Angeles,344.0,"[{'WhPerMile': 400, 'kWhRequested': 8.0, 'mile..."
5e23b149f9af8b5fe4b973d2,3,2020-01-02 13:59:58+00:00,2020-01-02 16:38:39+00:00,2020-01-02 15:18:45+00:00,2.355,1_1_193_820_2020-01-02 13:59:58.309319,1,AG-1F04,1-1-193-820,America/Los_Angeles,1117.0,"[{'WhPerMile': 400, 'kWhRequested': 8.0, 'mile..."
5e23b149f9af8b5fe4b973d3,4,2020-01-02 14:00:01+00:00,2020-01-02 22:08:40+00:00,2020-01-02 18:17:30+00:00,13.375,1_1_193_819_2020-01-02 14:00:00.779967,1,AG-1F06,1-1-193-819,America/Los_Angeles,334.0,"[{'WhPerMile': 400, 'kWhRequested': 16.0, 'mil..."
...,...,...,...,...,...,...,...,...,...,...,...,...
5d2fbdd3f9af8b4d0dd0d54a,8670,2019-07-01 21:49:12+00:00,2019-07-02 01:37:18+00:00,2019-07-01 23:14:33+00:00,8.399,1_1_179_798_2019-07-01 21:49:11.873404,1,AG-3F18,1-1-179-798,America/Los_Angeles,1346.0,"[{'WhPerMile': 400, 'kWhRequested': 32.0, 'mil..."
5d2fbdd3f9af8b4d0dd0d54b,8671,2019-07-01 21:58:45+00:00,2019-07-02 00:39:48+00:00,2019-07-02 00:40:21+00:00,16.864,1_1_179_794_2019-07-01 21:58:44.571011,1,AG-3F20,1-1-179-794,America/Los_Angeles,364.0,"[{'WhPerMile': 400, 'kWhRequested': 40.0, 'mil..."
5d2fbdd3f9af8b4d0dd0d54c,8672,2019-07-01 22:02:21+00:00,2019-07-02 00:58:50+00:00,2019-07-02 00:59:23+00:00,18.335,1_1_191_807_2019-07-01 22:02:20.810735,1,AG-4F47,1-1-191-807,America/Los_Angeles,2050.0,"[{'WhPerMile': 333, 'kWhRequested': 29.97, 'mi..."
5d2fbdd3f9af8b4d0dd0d54d,8673,2019-07-01 22:23:44+00:00,2019-07-02 02:03:36+00:00,2019-07-02 02:04:06+00:00,22.815,1_1_179_781_2019-07-01 22:23:32.496137,1,AG-3F31,1-1-179-781,America/Los_Angeles,1626.0,"[{'WhPerMile': 200, 'kWhRequested': 34.0, 'mil..."
5d2fbdd3f9af8b4d0dd0d54e,8674,2019-07-01 22:36:08+00:00,2019-07-02 01:10:52+00:00,2019-07-02 00:24:32+00:00,10.241,1_1_193_819_2019-07-01 22:35:56.104381,1,AG-1F06,1-1-193-819,America/Los_Angeles,2299.0,"[{'WhPerMile': 333, 'kWhRequested': 16.65, 'mi..."

## Descriptive Analytics

### Temporal Patterns and Seasonality

### Key Performance Indicators

### Site Characteristics

### Site Characteristics

## Cluster Analysis

## Utilization Prediction

### Predictive Model 1

### Predictive Model 2

### Business Case